name: Benchmark.Net GenericCSharpProgram
on:
  push:
    branches:
      - main

permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    name: Run Benchmark.Net benchmark GenericCSharpProgram
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0" # SDK Version to use. keep in line with examples/benchmarkdotnet/global.json
      - name: Run benchmark
        run: cd ./GenericCSharpProgram/ && dotnet run --exporters json --filter '*' -c Release --framework net6.0
      - name: Store benchmark result
        uses: rhysd/github-action-benchmark@v1
        with:
          name: Benchmark.Net Benchmark
          tool: "benchmarkdotnet"
          output-file-path: GenericCSharpProgram/BenchmarkDotNet.Artifacts/results/GenericCSharpProgram.Algorithms-report-full-compressed.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          # Show alert with commit comment on detecting possible performance regression
          alert-threshold: "200%"
          comment-on-alert: true
          fail-on-alert: true
          alert-comment-cc-users: "@${{ github.repository_owner }}"
          skip-fetch-gh-pages: true
