name: Benchmark.Net GenericCSharpProgram
on:
  push:
    branches:
      - main

permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    name: Run Benchmark.Net benchmark GenericCSharpProgram
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0" # SDK Version to use. keep in line with examples/benchmarkdotnet/global.json
      - name: Run benchmark
        run: cd ./GenericCSharpProgram/ && dotnet run --exporters json --filter '*' -c Release --framework net6.0
      - name: Zip
        run: |
          zip -r "GenericCSharpProgram.Algorithms" "./GenericCSharpProgram/BenchmarkDotNet.Artifacts/"
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: "GenericCSharpProgram.Algorithms"
          path: "GenericCSharpProgram.Algorithms.zip"
          retention-days: 7
      - name: Set Release version env variable
        run: |
          echo "RELEASE_VERSION=$(date "+%y.%m.%d")" >> $GITHUB_ENV
      - name: Automatic Releases
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ env.RELEASE_VERSION }}"
          prerelease: true
          title: "Release ${{ env.RELEASE_VERSION }}"
          files: |
            *.zip
