name: Benchmark.Net GenericCSharpProgram
on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    name: Run Benchmark.Net benchmark GenericCSharpProgram
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0" # SDK Version to use. keep in line with examples/benchmarkdotnet/global.json
      - name: Run benchmark
        run: cd ./GenericCSharpProgram/ && dotnet run --exporters json --filter '*' -c Release --framework net6.0
      - name: Zip
        run: |
          zip -r "GenericCSharpProgram.Algorithms.zip" "./GenericCSharpProgram/BenchmarkDotNet.Artifacts/"
      - name: Set Release version env variable
        id: release-selector
        run: |
          echo "RELEASE_VERSION=$(date "+%y.%m.%d-%H:$M")" >> $GITHUB_OUTPUT
      - name: Automatic Releases
        uses: marvinpinto/action-automatic-releases@v1.2.1
        env:
          RELEASE_VERSION: ${{ steps.release-selector.outputs.RELEASE_VERSION }}
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ env.RELEASE_VERSION }}"
          prerelease: false
          title: "Benchmark.Net Result ${{ env.RELEASE_VERSION }}"
          files: |
            ./GenericCSharpProgram.Algorithms.zip
